### ISSUE TITLE
SS9008 suggested name can't be inferred due to the wrong expression

### ISSUE THREAD

**Issue by SunnieShine** [SunnieShine/Sudoku#151]
Wrong detail:

```
Severity	Code	Description	Project	File	Line	Suppression State
Warning	AD0001	Analyzer 'Sudoku.Diagnostics.CodeAnalysis.Analyzers.ForLoopBadConditionAnalyzer' threw an exception of type 'System.ArgumentException' with message 'The specified argument is invalid name to convert.
Parameter name: this'.
Exception occurred with following context:
Compilation: Sudoku.Solving
SyntaxTree: P:\Projects\Common\Sudoku\src\Sudoku.Solving\Solving\Manual\Symmetry\GspStepSearcher.Implementation.cs
SyntaxNode: for (int j = 0; j < 8 - i; j++) ... [ForStatementSyntax]@[3802..4821) (169,4)-(221,5)

System.ArgumentException: The specified argument is invalid name to convert.
Parameter name: this
   at Sudoku.Diagnostics.CodeAnalysis.Extensions.StringEx.ToCamelCase(String this, CaseConvertingOption caseConvertingOption)
   at Sudoku.Diagnostics.CodeAnalysis.Analyzers.ForLoopBadConditionAnalyzer.AnalyzeSyntaxNodeRecursively(SyntaxNodeAnalysisContext& context, ForStatementSyntax forStatement, SyntaxNode originalNode, SemanticModel semanticModel, CancellationToken& cancellationToken)
   at Sudoku.Diagnostics.CodeAnalysis.Analyzers.ForLoopBadConditionAnalyzer.AnalyzeSyntaxNode(SyntaxNodeAnalysisContext context)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
   at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
-----

Suppress the following diagnostics to disable this analyzer: SS9001	Sudoku.Solving		1	Active
```

**Comment by SunnieShine** [comment]
Here we'll change the API `ToCamelCase` method to change its behavior. At present we'll return `null` when the result name can't be inferred rather than throw an exception.
